//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://xerox.com/eurasia/xi/CRM/GDO", ConfigurationName="mi_out_gdo_ws305_get_materials")]
public interface mi_out_gdo_ws305_get_materials
{
    
    // CODEGEN: Generating message contract since the operation mi_out_gdo_ws305_get_materials is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    mi_out_gdo_ws305_get_materialsResponse mi_out_gdo_ws305_get_materials(mi_out_gdo_ws305_get_materialsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    System.Threading.Tasks.Task<mi_out_gdo_ws305_get_materialsResponse> mi_out_gdo_ws305_get_materialsAsync(mi_out_gdo_ws305_get_materialsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZXR_WS305_GET_MATERIALS
{
    
    private ZMATNR[] iT_MATNRField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZMATNR[] IT_MATNR
    {
        get
        {
            return this.iT_MATNRField;
        }
        set
        {
            this.iT_MATNRField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZMATNR
{
    
    private string mATNRField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string MATNR
    {
        get
        {
            return this.mATNRField;
        }
        set
        {
            this.mATNRField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZMATNR_DATA_LINE
{
    
    private string mATNRField;
    
    private string dESCRField;
    
    private string mAT_GRField;
    
    private string uNITField;
    
    private decimal pRICEField;
    
    private string pR_DATEField;
    
    private decimal mOLCOMField;
    
    private string mSGTYField;
    
    private string mSGTXField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string MATNR
    {
        get
        {
            return this.mATNRField;
        }
        set
        {
            this.mATNRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string DESCR
    {
        get
        {
            return this.dESCRField;
        }
        set
        {
            this.dESCRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string MAT_GR
    {
        get
        {
            return this.mAT_GRField;
        }
        set
        {
            this.mAT_GRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string UNIT
    {
        get
        {
            return this.uNITField;
        }
        set
        {
            this.uNITField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public decimal PRICE
    {
        get
        {
            return this.pRICEField;
        }
        set
        {
            this.pRICEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string PR_DATE
    {
        get
        {
            return this.pR_DATEField;
        }
        set
        {
            this.pR_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public decimal MOLCOM
    {
        get
        {
            return this.mOLCOMField;
        }
        set
        {
            this.mOLCOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string MSGTY
    {
        get
        {
            return this.mSGTYField;
        }
        set
        {
            this.mSGTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string MSGTX
    {
        get
        {
            return this.mSGTXField;
        }
        set
        {
            this.mSGTXField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
public partial class ZXR_WS305_GET_MATERIALSResponse
{
    
    private ZMATNR_DATA_LINE[] eT_MATNRField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZMATNR_DATA_LINE[] ET_MATNR
    {
        get
        {
            return this.eT_MATNRField;
        }
        set
        {
            this.eT_MATNRField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class mi_out_gdo_ws305_get_materialsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
    public ZXR_WS305_GET_MATERIALS ZXR_WS305_GET_MATERIALS;
    
    public mi_out_gdo_ws305_get_materialsRequest()
    {
    }
    
    public mi_out_gdo_ws305_get_materialsRequest(ZXR_WS305_GET_MATERIALS ZXR_WS305_GET_MATERIALS)
    {
        this.ZXR_WS305_GET_MATERIALS = ZXR_WS305_GET_MATERIALS;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class mi_out_gdo_ws305_get_materialsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
    public ZXR_WS305_GET_MATERIALSResponse ZXR_WS305_GET_MATERIALSResponse;
    
    public mi_out_gdo_ws305_get_materialsResponse()
    {
    }
    
    public mi_out_gdo_ws305_get_materialsResponse(ZXR_WS305_GET_MATERIALSResponse ZXR_WS305_GET_MATERIALSResponse)
    {
        this.ZXR_WS305_GET_MATERIALSResponse = ZXR_WS305_GET_MATERIALSResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface mi_out_gdo_ws305_get_materialsChannel : mi_out_gdo_ws305_get_materials, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class mi_out_gdo_ws305_get_materialsClient : System.ServiceModel.ClientBase<mi_out_gdo_ws305_get_materials>, mi_out_gdo_ws305_get_materials
{
    
    public mi_out_gdo_ws305_get_materialsClient()
    {
    }
    
    public mi_out_gdo_ws305_get_materialsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public mi_out_gdo_ws305_get_materialsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public mi_out_gdo_ws305_get_materialsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public mi_out_gdo_ws305_get_materialsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    mi_out_gdo_ws305_get_materialsResponse mi_out_gdo_ws305_get_materials.mi_out_gdo_ws305_get_materials(mi_out_gdo_ws305_get_materialsRequest request)
    {
        return base.Channel.mi_out_gdo_ws305_get_materials(request);
    }
    
    public ZXR_WS305_GET_MATERIALSResponse mi_out_gdo_ws305_get_materials(ZXR_WS305_GET_MATERIALS ZXR_WS305_GET_MATERIALS)
    {
        mi_out_gdo_ws305_get_materialsRequest inValue = new mi_out_gdo_ws305_get_materialsRequest();
        inValue.ZXR_WS305_GET_MATERIALS = ZXR_WS305_GET_MATERIALS;
        mi_out_gdo_ws305_get_materialsResponse retVal = ((mi_out_gdo_ws305_get_materials)(this)).mi_out_gdo_ws305_get_materials(inValue);
        return retVal.ZXR_WS305_GET_MATERIALSResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<mi_out_gdo_ws305_get_materialsResponse> mi_out_gdo_ws305_get_materials.mi_out_gdo_ws305_get_materialsAsync(mi_out_gdo_ws305_get_materialsRequest request)
    {
        return base.Channel.mi_out_gdo_ws305_get_materialsAsync(request);
    }
    
    public System.Threading.Tasks.Task<mi_out_gdo_ws305_get_materialsResponse> mi_out_gdo_ws305_get_materialsAsync(ZXR_WS305_GET_MATERIALS ZXR_WS305_GET_MATERIALS)
    {
        mi_out_gdo_ws305_get_materialsRequest inValue = new mi_out_gdo_ws305_get_materialsRequest();
        inValue.ZXR_WS305_GET_MATERIALS = ZXR_WS305_GET_MATERIALS;
        return ((mi_out_gdo_ws305_get_materials)(this)).mi_out_gdo_ws305_get_materialsAsync(inValue);
    }
}
