//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://xerox.com/eurasia/xi/CRM/GDO", ConfigurationName="mi_out_gdo_ws136_purch_req_create")]
public interface mi_out_gdo_ws136_purch_req_create
{
    
    // CODEGEN: Generating message contract since the operation mi_out_gdo_ws136_purch_req_create is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    mi_out_gdo_ws136_purch_req_createResponse mi_out_gdo_ws136_purch_req_create(mi_out_gdo_ws136_purch_req_createRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
    System.Threading.Tasks.Task<mi_out_gdo_ws136_purch_req_createResponse> mi_out_gdo_ws136_purch_req_createAsync(mi_out_gdo_ws136_purch_req_createRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
public partial class ZGdoWs136PurchReqCreate
{
    
    private ZgdoPrItemCr[] itPrItemField;
    
    private string ivCrmIdField;
    
    private string ivDateField;
    
    private string ivMContractIdField;
    
    private string ivPrTypeField;
    
    private string ivUrgencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ZgdoPrItemCr[] ItPrItem
    {
        get
        {
            return this.itPrItemField;
        }
        set
        {
            this.itPrItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string IvCrmId
    {
        get
        {
            return this.ivCrmIdField;
        }
        set
        {
            this.ivCrmIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string IvDate
    {
        get
        {
            return this.ivDateField;
        }
        set
        {
            this.ivDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string IvMContractId
    {
        get
        {
            return this.ivMContractIdField;
        }
        set
        {
            this.ivMContractIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string IvPrType
    {
        get
        {
            return this.ivPrTypeField;
        }
        set
        {
            this.ivPrTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string IvUrgency
    {
        get
        {
            return this.ivUrgencyField;
        }
        set
        {
            this.ivUrgencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
public partial class ZgdoPrItemCr
{
    
    private string prItemIdField;
    
    private string lgortField;
    
    private string matnrField;
    
    private string batchField;
    
    private string matGrField;
    
    private decimal quantityField;
    
    private string unitField;
    
    private string zzgdoIncidentField;
    
    private string zzgdoReasonField;
    
    private string tdlineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string PrItemId
    {
        get
        {
            return this.prItemIdField;
        }
        set
        {
            this.prItemIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Lgort
    {
        get
        {
            return this.lgortField;
        }
        set
        {
            this.lgortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string Matnr
    {
        get
        {
            return this.matnrField;
        }
        set
        {
            this.matnrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string Batch
    {
        get
        {
            return this.batchField;
        }
        set
        {
            this.batchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string MatGr
    {
        get
        {
            return this.matGrField;
        }
        set
        {
            this.matGrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public decimal Quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string Unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public string ZzgdoIncident
    {
        get
        {
            return this.zzgdoIncidentField;
        }
        set
        {
            this.zzgdoIncidentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
    public string ZzgdoReason
    {
        get
        {
            return this.zzgdoReasonField;
        }
        set
        {
            this.zzgdoReasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
    public string Tdline
    {
        get
        {
            return this.tdlineField;
        }
        set
        {
            this.tdlineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
public partial class Zmessage
{
    
    private string msgtyField;
    
    private string msgidField;
    
    private string msgnoField;
    
    private string msgtxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string Msgty
    {
        get
        {
            return this.msgtyField;
        }
        set
        {
            this.msgtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string Msgid
    {
        get
        {
            return this.msgidField;
        }
        set
        {
            this.msgidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string Msgno
    {
        get
        {
            return this.msgnoField;
        }
        set
        {
            this.msgnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string Msgtx
    {
        get
        {
            return this.msgtxField;
        }
        set
        {
            this.msgtxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.4161.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
public partial class ZGdoWs136PurchReqCreateResponse
{
    
    private Zmessage[] etReturnField;
    
    private string evPrIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Zmessage[] EtReturn
    {
        get
        {
            return this.etReturnField;
        }
        set
        {
            this.etReturnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string EvPrId
    {
        get
        {
            return this.evPrIdField;
        }
        set
        {
            this.evPrIdField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class mi_out_gdo_ws136_purch_req_createRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
    public ZGdoWs136PurchReqCreate ZGdoWs136PurchReqCreate;
    
    public mi_out_gdo_ws136_purch_req_createRequest()
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createRequest(ZGdoWs136PurchReqCreate ZGdoWs136PurchReqCreate)
    {
        this.ZGdoWs136PurchReqCreate = ZGdoWs136PurchReqCreate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class mi_out_gdo_ws136_purch_req_createResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
    public ZGdoWs136PurchReqCreateResponse ZGdoWs136PurchReqCreateResponse;
    
    public mi_out_gdo_ws136_purch_req_createResponse()
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createResponse(ZGdoWs136PurchReqCreateResponse ZGdoWs136PurchReqCreateResponse)
    {
        this.ZGdoWs136PurchReqCreateResponse = ZGdoWs136PurchReqCreateResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface mi_out_gdo_ws136_purch_req_createChannel : mi_out_gdo_ws136_purch_req_create, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class mi_out_gdo_ws136_purch_req_createClient : System.ServiceModel.ClientBase<mi_out_gdo_ws136_purch_req_create>, mi_out_gdo_ws136_purch_req_create
{
    
    public mi_out_gdo_ws136_purch_req_createClient()
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public mi_out_gdo_ws136_purch_req_createClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    mi_out_gdo_ws136_purch_req_createResponse mi_out_gdo_ws136_purch_req_create.mi_out_gdo_ws136_purch_req_create(mi_out_gdo_ws136_purch_req_createRequest request)
    {
        return base.Channel.mi_out_gdo_ws136_purch_req_create(request);
    }
    
    public ZGdoWs136PurchReqCreateResponse mi_out_gdo_ws136_purch_req_create(ZGdoWs136PurchReqCreate ZGdoWs136PurchReqCreate)
    {
        mi_out_gdo_ws136_purch_req_createRequest inValue = new mi_out_gdo_ws136_purch_req_createRequest();
        inValue.ZGdoWs136PurchReqCreate = ZGdoWs136PurchReqCreate;
        mi_out_gdo_ws136_purch_req_createResponse retVal = ((mi_out_gdo_ws136_purch_req_create)(this)).mi_out_gdo_ws136_purch_req_create(inValue);
        return retVal.ZGdoWs136PurchReqCreateResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<mi_out_gdo_ws136_purch_req_createResponse> mi_out_gdo_ws136_purch_req_create.mi_out_gdo_ws136_purch_req_createAsync(mi_out_gdo_ws136_purch_req_createRequest request)
    {
        return base.Channel.mi_out_gdo_ws136_purch_req_createAsync(request);
    }
    
    public System.Threading.Tasks.Task<mi_out_gdo_ws136_purch_req_createResponse> mi_out_gdo_ws136_purch_req_createAsync(ZGdoWs136PurchReqCreate ZGdoWs136PurchReqCreate)
    {
        mi_out_gdo_ws136_purch_req_createRequest inValue = new mi_out_gdo_ws136_purch_req_createRequest();
        inValue.ZGdoWs136PurchReqCreate = ZGdoWs136PurchReqCreate;
        return ((mi_out_gdo_ws136_purch_req_create)(this)).mi_out_gdo_ws136_purch_req_createAsync(inValue);
    }
}
